# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "alexsmobs:snow_leopard",
    "villagergolemhealer:villagergolemhealer",
    "alshanex_familiars:blue_bird",
    "irons_spellbooks:archevoker",
    "endermanoverhaul:flower_fields_enderman",
    "villagergolemhealer:minigolem",
    "irons_spellbooks:catacombs_zombie",
    "illageandspillage:skull_bomb",
    "endermanoverhaul:desert_enderman",
    "ars_nouveau:familiar_wixie",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "illageandspillage:trick_or_treat",
    "herios_helian_mod:helian_blacksmith",
    "legendarycreatures:wisp",
    "minecraft:llama",
    "biomeswevegone:man_o_war",
    "alexsmobs:skreecher",
    "minecraft:tadpole",
    "alshanex_familiars:druid_pet",
    "illageandspillage:imp",
    "aquamirae:maw",
    "tameablebeasts:quetzalcoatlus",
    "luminous_nether:basalt_executioner",
    "alexsmobs:hammerhead_shark",
    "herios_helian_mod:helian_warrior",
    "alexsmobs:grizzly_bear",
    "alexsmobs:murmur_head",
    "creature_compendium:unseen_grasp",
    "illageandspillage:old_magispeller",
    "legendarycreatures:peacock_spider",
    "ars_nouveau:gift_starby",
    "illageandspillage:eyesore",
    "minecraft:mooshroom",
    "sweet_calamity:sweet_witch",
    "minecraft:axolotl",
    "illageandspillage:beeper",
    "irons_spellbooks:summoned_vex",
    "alexsmobs:gorilla",
    "alshanex_familiars:sleeping_plague_pet",
    "illageandspillage:old_freakager",
    "alexsmobs:cosmic_cod",
    "ars_nouveau:drygmy",
    "alshanex_familiars:plague_pet",
    "arkane_domains:mummy_cat_entity",
    "alexsmobs:kangaroo",
    "endermanoverhaul:hammerhead_pet_enderman",
    "creeperoverhaul:spruce_creeper",
    "sweet_calamity:sweetened_pig",
    "legendarycreatures:nether_wisp",
    "ars_nouveau:wilden_boss",
    "alexsmobs:hummingbird",
    "iceandfire:siren",
    "luminous_nether:soul_furnace",
    "alexsmobs:crow",
    "alexsmobs:guster",
    "luminous_nether:the_furnace_2",
    "luminous_nether:the_furnace_3",
    "luminous_nether:piglin_ghost",
    "sweet_calamity:creaking_clown",
    "irons_spellbooks:magehunter_vindicator",
    "sweet_calamity:gomurro",
    "medievalry:undead_knight",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "iceandfire:dread_knight",
    "illageandspillage:crocofang",
    "alexsmobs:emu",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "illageandspillage:spirit_hand",
    "ars_nouveau:cascading_weald_walker",
    "sweet_calamity:candy_knight",
    "iceandfire:myrmex_swarmer",
    "sweet_calamity:bomber_cherry",
    "legendarycreatures:ender_wisp",
    "minecraft:zombified_piglin",
    "illageandspillage:boss_randomizer",
    "medievalry:ghoul",
    "minecraft:sheep",
    "herios_helian_mod:helian_sprite",
    "beggars:witch_beggar",
    "aquatica:wreeper",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "iceandfire:myrmex_soldier",
    "arkane_domains:resurrected_guard",
    "alshanex_familiars:sleeping_summoner_pet",
    "ars_nouveau:whirlisprig",
    "tameablebeasts:crested_gecko",
    "iceandfire:pixie",
    "realmrpg_demons:demon",
    "luminous_nether:warped_spewer",
    "crittersandcompanions:dragonfly",
    "alexsmobs:mudskipper",
    "iceandfire:myrmex_sentinel",
    "luminous_nether:soul_ember",
    "realmrpg_demons:demon_minion",
    "alexsmobs:crimson_mosquito",
    "creeperoverhaul:beach_creeper",
    "creeperoverhaul:hills_creeper",
    "alexsmobs:jerboa",
    "crittersandcompanions:otter",
    "endermanoverhaul:spirit",
    "alexsmobs:comb_jelly",
    "creeperoverhaul:bamboo_creeper",
    "brewery:beer_elemental",
    "inka:viraicocha_magic_square",
    "alexsmobs:enderiophage",
    "tameablebeasts:tameable_penguin",
    "alexsmobs:sunbird",
    "illageandspillage:old_ragno",
    "iceandfire:myrmex_worker",
    "minecraft:cat",
    "ars_nouveau:amethyst_golem",
    "arkane_domains:reanimated",
    "alshanex_familiars:mage_pet",
    "minecraft:tropical_fish",
    "illageandspillage:hinder",
    "realmrpg_demons:imp_guard",
    "sweet_calamity:bittersweet",
    "realmrpg_demons:ancient_demon_lord",
    "minecraft:zombie_villager",
    "luminous_nether:piglin_executioner_2",
    "luminous_nether:piglin_executioner_3",
    "sweet_calamity:cake_penguin",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "alexsmobs:seagull",
    "mowziesmobs:lantern",
    "endermanoverhaul:end_enderman",
    "endermanoverhaul:soulsand_valley_enderman",
    "aquamirae:tortured_soul",
    "alshanex_familiars:summoner_pet",
    "ars_nouveau:wilden_stalker",
    "creeperoverhaul:cave_creeper",
    "sweet_calamity:cotton_candy_cow",
    "minecraft:husk",
    "tameablebeasts:beetle_drone",
    "inka:viraicocha_sun",
    "alshanex_familiars:scorcher_pet",
    "mowziesmobs:umvuthana",
    "creature_compendium:moleman",
    "luminous_nether:ember",
    "call_of_yucutan:golden_guard",
    "luminous_nether:piglin_executioner",
    "minecraft:donkey",
    "mowziesmobs:umvuthana_crane_player",
    "minecraft:piglin_brute",
    "aquamirae:golden_moth",
    "alexsmobs:frilled_shark",
    "alshanex_familiars:sleeping_mage_pet",
    "alexsmobs:bald_eagle",
    "luminous_nether:glider",
    "endermanoverhaul:scarab",
    "iceandfire:ice_dragon",
    "alexsmobs:blobfish",
    "alexsmobs:void_worm",
    "minecraft:parrot",
    "aquamirae:spinefish",
    "irons_spellbooks:apothecarist",
    "call_of_yucutan:kukulkan",
    "illageandspillage:pumpkin_bomb",
    "illageandspillage:engineer",
    "alexsmobs:centipede_head",
    "immortalgingerbread:spoiled_snowman",
    "illageandspillage:scythe",
    "call_of_yucutan:undead_warrior",
    "alshanex_familiars:summoned_shadow",
    "creeperoverhaul:desert_creeper",
    "iceandfire:sea_serpent",
    "alexsmobs:banana_slug",
    "alexsmobs:bunfungus",
    "luminous_nether:the_furnace",
    "illageandspillage:poker",
    "inka:vibration_entity",
    "tameablebeasts:tameable_racoon",
    "minecraft:mule",
    "ribbits:ribbit",
    "minecraft:vindicator",
    "call_of_yucutan:chaac",
    "alexsmobs:flying_fish",
    "crittersandcompanions:leaf_insect",
    "creeperoverhaul:mushroom_creeper",
    "luminous_nether:piglin_cultist_leader",
    "tameablebeasts:giant_roly_poly",
    "irons_spellbooks:debug_wizard",
    "irons_spellbooks:spectral_steed",
    "tameablebeasts:giant_grasshopper",
    "legendarycreatures:scorpion_baby",
    "ars_nouveau:familiar_whirlisprig",
    "inka:viraicocha_solar_beam",
    "tombstone:grave_guardian",
    "creeperoverhaul:badlands_creeper",
    "creeperoverhaul:snowy_creeper",
    "illageandspillage:funnybone",
    "alexsmobs:terrapin",
    "aquamirae:luminous_jelly",
    "mowziesmobs:bluff",
    "tameablebeasts:scarecrow_allay",
    "iceandfire:lightning_dragon",
    "realmrpg_demons:imp",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "creeperoverhaul:swamp_creeper",
    "endermanoverhaul:crimson_forest_enderman",
    "iceandfire:fire_dragon",
    "minecraft:cod",
    "alexsmobs:platypus",
    "luminous_nether:mushlin_spewer_3",
    "luminous_nether:mushlin_spewer_2",
    "legendarycreatures:scorpion",
    "illageandspillage:magispeller",
    "minecraft:cow",
    "alshanex_familiars:illusionist_pet",
    "alexsmobs:rocky_roller",
    "alshanex_familiars:sleeping_hunter_pet",
    "alexsmobs:soul_vulture",
    "alexsmobs:blue_jay",
    "luminous_nether:revenant_skeleton",
    "iceandfire:dread_scuttler",
    "minecraft:salmon",
    "crittersandcompanions:dumbo_octopus",
    "mowziesmobs:naga",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "mowziesmobs:ferrous_wroughtnaut",
    "minecraft:rabbit",
    "minecraft:pillager",
    "herios_helian_mod:helian",
    "minecraft:zoglin",
    "alexsmobs:leafcutter_ant",
    "tameablebeasts:ground_beetle",
    "ars_nouveau:wilden_guardian",
    "illageandspillage:factory",
    "aquamirae:captain_cornelia",
    "creeperoverhaul:jungle_creeper",
    "irons_spellbooks:cryomancer",
    "illageandspillage:dispenser",
    "alshanex_familiars:hunter_pet",
    "iceandfire:gorgon",
    "illageandspillage:spiritcaller",
    "inka:viraicocha_solar_shot",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "endermanoverhaul:windswept_hills_enderman",
    "tameablebeasts:graptera",
    "iceandfire:cockatrice",
    "alshanex_familiars:necromancer_pet",
    "beggars:zombie_beggar",
    "sweet_calamity:creamy",
    "endermanoverhaul:end_islands_enderman",
    "realmrpg_demons:chort",
    "mowziesmobs:umvuthana_follower_player",
    "alshanex_familiars:archmage_pet",
    "iceandfire:deathworm",
    "illageandspillage:kaboomer",
    "tameablebeasts:tameable_beetle",
    "endermanoverhaul:warped_forest_enderman",
    "alexsmobs:seal",
    "inka:viraicocha_sun_projectile",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "irons_spellbooks:necromancer",
    "alshanex_familiars:sleeping_druid_pet",
    "iceandfire:dread_lich",
    "alexsmobs:maned_wolf",
    "minecraft:dolphin",
    "endermanoverhaul:badlands_enderman",
    "alexsmobs:gelada_monkey",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "crittersandcompanions:jumping_spider",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "herios_helian_mod:helian_redstoner",
    "minecraft:illusioner",
    "tombstone:spectral_wolf",
    "luminous_nether:crimson_walker",
    "endermanoverhaul:axolotl_pet_enderman",
    "takesapillage:skirmisher",
    "alexsmobs:bison",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "creature_compendium:netherite_forge",
    "alshanex_familiars:sleeping_illusionist_pet",
    "alexsmobs:tusklin",
    "legendarycreatures:scarecrow",
    "alexsmobs:underminer",
    "minecraft:wandering_trader",
    "luminous_nether:zombie_piglin_cultist",
    "biomeswevegone:oddion",
    "luminous_nether:zombie_piglin_cultist_leader",
    "alshanex_familiars:sleeping_bard_pet",
    "aquatica:telescope_leviathan",
    "arkane_domains:bomb",
    "herios_helian_mod:helian_miner",
    "iceandfire:stone_statue",
    "crittersandcompanions:sea_bunny",
    "illageandspillage:illager_soul",
    "mowziesmobs:umvuthana_raptor",
    "crittersandcompanions:red_panda",
    "endermanoverhaul:cave_enderman",
    "endermanoverhaul:mushroom_fields_enderman",
    "minecraft:pufferfish",
    "minecraft:fox",
    "illageandspillage:magi_heal",
    "mowziesmobs:umvuthana_crane",
    "call_of_yucutan:ahaw",
    "alexsmobs:warped_toad",
    "illageandspillage:old_axe",
    "alshanex_familiars:sleeping_archmage_pet",
    "arkane_domains:beetle",
    "alexsmobs:cockroach",
    "creeperoverhaul:savannah_creeper",
    "chocobos:chocobo",
    "tameablebeasts:tameable_chikote",
    "inka:particlesviraicocha",
    "endermanoverhaul:pet_enderman",
    "alexsmobs:capuchin_monkey",
    "minecraft:polar_bear",
    "alshanex_familiars:sleeping_scorcher_pet",
    "inka:incawarrior_2",
    "inka:incawarrior_1",
    "illageandspillage:mob_spirit",
    "inka:incawarrior_3",
    "endermanoverhaul:ice_spikes_enderman",
    "minecraft:turtle",
    "alexsmobs:rattlesnake",
    "ars_nouveau:familiar_starbuncle",
    "ars_nouveau:starbuncle",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "irons_spellbooks:dead_king",
    "legendarycreatures:corpse_eater",
    "alexsmobs:straddler",
    "alexsmobs:sea_bear",
    "call_of_yucutan:updater",
    "mowziesmobs:umvuthana_follower_raptor",
    "alexsmobs:sugar_glider",
    "illageandspillage:axe",
    "endermanoverhaul:swamp_enderman",
    "aquamirae:eel",
    "alexsmobs:orca",
    "illageandspillage:faker",
    "irons_spellbooks:priest",
    "iceandfire:troll",
    "legendarycreatures:desert_mojo",
    "illageandspillage:twittollager",
    "inka:headclava",
    "illageandspillage:villager_soul",
    "chest_with_legs:chester",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "iceandfire:amphithere",
    "ars_nouveau:familiar_amethyst_golem",
    "illageandspillage:web",
    "illageandspillage:bone",
    "alexsmobs:skunk",
    "aquamirae:anglerfish",
    "rpg_companions_tiny_dragons:tiny_dragon_03",
    "rpg_companions_tiny_dragons:tiny_dragon_02",
    "rpg_companions_tiny_dragons:tiny_dragon_01",
    "rpg_companions_tiny_dragons:tiny_dragon_07",
    "rpg_companions_tiny_dragons:tiny_dragon_06",
    "arkane_domains:gerro_3",
    "inka:cuy",
    "rpg_companions_tiny_dragons:tiny_dragon_05",
    "alexsmobs:tasmanian_devil",
    "rpg_companions_tiny_dragons:tiny_dragon_04",
    "rpg_companions_tiny_dragons:tiny_dragon_09",
    "rpg_companions_tiny_dragons:tiny_dragon_08",
    "sweet_calamity:ice_cream_penguin",
    "alexsmobs:stradpole",
    "herios_helian_mod:helian_golem",
    "herios_helian_mod:helian_empress",
    "iceandfire:stymphalian_bird",
    "luminous_nether:mushlin_spewer",
    "iceandfire:hippogryph",
    "endermanoverhaul:savanna_enderman",
    "rpg_companions_tiny_dragons:tiny_dragon_10",
    "tameablebeasts:argentavis",
    "arkane_domains:gebero",
    "minecraft:panda",
    "endermanoverhaul:coral_enderman",
    "alshanex_familiars:sleeping_necromancer_pet",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "illageandspillage:igniter",
    "inka:capac",
    "alexsmobs:farseer",
    "ars_nouveau:vexing_weald_walker",
    "luminous_nether:mushlin_bumper",
    "illageandspillage:ragno",
    "alexsmobs:warped_mosco",
    "inka:quake_entity",
    "iceandfire:cyclops",
    "alexsmobs:komodo_dragon",
    "realmrpg_demons:demon_lord",
    "endermanoverhaul:dark_oak_enderman",
    "aquamirae:maze_mother",
    "sweet_calamity:dulce_de_leche_creeper",
    "illageandspillage:sniper",
    "irons_spellbooks:summoned_polar_bear",
    "alexsmobs:crocodile",
    "irons_spellbooks:cultist",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "inka:apuinti",
    "alexsmobs:mimicube",
    "illageandspillage:web_net",
    "call_of_yucutan:mitnal_monkey",
    "illageandspillage:crashager",
    "ars_nouveau:familiar_bookwyrm",
    "minecraft:frog",
    "crittersandcompanions:shima_enaga",
    "alexsmobs:mimic_octopus",
    "legendarycreatures:bullfrog",
    "arkane_domains:brillo",
    "alexsmobs:void_worm_part",
    "tameablebeasts:fur_golem",
    "legendarycreatures:hound",
    "iceandfire:hydra",
    "aquamirae:pillagers_patrol",
    "luminous_nether:gilded_cultist",
    "illageandspillage:chagrin_sentry",
    "minecraft:evoker",
    "iceandfire:dread_ghoul",
    "alexsmobs:tarantula_hawk",
    "crittersandcompanions:ferret",
    "ars_nouveau:blazing_weald_walker",
    "alexsmobs:cachalot_whale",
    "beggars:villager_beggar",
    "endermanoverhaul:nether_wastes_enderman",
    "creeperoverhaul:ocean_creeper",
    "creeperoverhaul:dark_oak_creeper",
    "takesapillage:legioner",
    "ars_nouveau:wilden_hunter",
    "iceandfire:dread_horse",
    "alexsmobs:anaconda",
    "irons_spellbooks:summoned_zombie",
    "arkane_domains:cursed_pharaoh",
    "mowziesmobs:grottol",
    "creature_compendium:unseen_hand",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "illageandspillage:illashooter",
    "iceandfire:dread_beast",
    "alexsmobs:mantis_shrimp",
    "alshanex_familiars:cleric_pet",
    "luminous_nether:piglin_cultist",
    "endermanoverhaul:snowy_enderman",
    "mowziesmobs:umvuthi",
    "inka:viraicocha",
    "iceandfire:hippocampus",
    "ars_nouveau:familiar_drygmy",
    "alexsmobs:toucan",
    "iceandfire:myrmex_queen",
    "luminous_nether:cultist_archer",
    "ars_nouveau:flourishing_weald_walker",
    "iceandfire:ghost",
    "luminous_nether:cultist_rider",
    "iceandfire:myrmex_royal",
    "irons_spellbooks:pyromancer",
    "alexsmobs:murmur",
    "arkane_domains:dark_shaman",
    "call_of_yucutan:blowgun_huracan",
    "creeperoverhaul:dripstone_creeper",
    "irons_spellbooks:summoned_skeleton",
    "iceandfire:dread_thrall",
    "ars_nouveau:summon_skeleton",
    "alexsmobs:mungus",
    "crittersandcompanions:koi_fish",
    "alshanex_familiars:bard_pet",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "irons_spellbooks:citadel_keeper",
    "ars_nouveau:summon_horse",
    "alexsmobs:catfish",
    "minecraft:piglin",
    "luminous_nether:ghost",
    "alexsmobs:skelewag",
    "takesapillage:archer",
    "alexsmobs:elephant",
    "illageandspillage:absorber",
    "illageandspillage:old_scythe",
    "call_of_yucutan:ah_puch",
    "herios_helian_mod:helian_painter",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "legendarycreatures:forest_mojo",
    "illageandspillage:preserver",
    "ars_nouveau:summon_wolf",
    "minecraft:ocelot",
    "chest_with_legs:hutch",
    "minecraft:wolf",
    "alshanex_familiars:sleeping_cleric_pet",
    "illageandspillage:freakager"
]
